package birra.modelo.dominio;

// default package
// Generated 02/10/2017 17:46:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import birra.modelo.tipificaciones.IPersistible;

/**
 * Sponsor generated by hbm2java
 */
@Entity
@Table(name = "categorianoticia")
public class CategoriaNoticia implements java.io.Serializable, IPersistible {
	
	private Integer idCategoriaNoticia;
	private String descripcion;

	public CategoriaNoticia() {
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategoriaNoticia", unique = true, nullable = false)
	public Integer getIdCategoriaNoticia() {
		return this.idCategoriaNoticia;
	}

	public void setIdCategoriaNoticia(Integer idCategoriaNoticia) {
		this.idCategoriaNoticia = idCategoriaNoticia;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	

}
