package birra.modelo.dominio;

// default package
// Generated 02/10/2017 17:46:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import birra.modelo.tipificaciones.IPersistible;
import birra.modelo.utiles.Constantes;
import net.sourceforge.stripes.action.FileBean;

/**
 * Sponsor generated by hbm2java
 */
@Entity
@Table(name = "sponsor")
public class Sponsor implements java.io.Serializable, IPersistible {
	
	private Integer idSponsor;
	private String nombre;
	private String breveDescripcion;
	private String linkGoogleMaps;
	private String direccion;
	private String descripcion;
	private String telefono;
	private String mail;
	private String linkFacebook;
	private String linkTwitter;
	private String linkWeb;	
	private boolean publicada; 
	
	private FileBean logo;
	private FileBean fondo;
	private String imagenLogo;
	private String imagenFondo;
	
	private Set<Imagen> imagens = new HashSet<Imagen>(0);

	public Sponsor() {
	}

	public Sponsor(String nombre, String linkGoogleMaps, String direccion, String descripcion,
			String telefono, String mail, String linkFacebook, String linkTwitter, String linkWeb) {
		this.nombre = nombre;
		this.linkGoogleMaps = linkGoogleMaps;
		this.direccion = direccion;
		this.descripcion = descripcion;
		this.telefono = telefono;
		this.mail = mail;
		this.linkFacebook = linkFacebook;
		this.linkTwitter = linkTwitter;
		this.linkWeb = linkWeb;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSponsor", unique = true, nullable = false)
	public Integer getIdSponsor() {
		return this.idSponsor;
	}

	public void setIdSponsor(Integer idSponsor) {
		this.idSponsor = idSponsor;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "linkGoogleMaps", length = 200)
	public String getLinkGoogleMaps() {
		return this.linkGoogleMaps;
	}

	public void setLinkGoogleMaps(String linkGoogleMaps) {
		this.linkGoogleMaps = linkGoogleMaps;
	}

	@Column(name = "direccion", length = 600)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "descripcion", length = 2000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "telefono", length = 100)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "mail", length = 100)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "linkFacebook", length = 150)
	public String getLinkFacebook() {
		return this.linkFacebook;
	}

	public void setLinkFacebook(String linkFacebook) {
		this.linkFacebook = linkFacebook;
	}

	@Column(name = "linkTwitter", length = 150)
	public String getLinkTwitter() {
		return this.linkTwitter;
	}

	public void setLinkTwitter(String linkTwitter) {
		this.linkTwitter = linkTwitter;
	}

	@Column(name = "linkWeb", length = 150)
	public String getLinkWeb() {
		return this.linkWeb;
	}

	public void setLinkWeb(String linkWeb) {
		this.linkWeb = linkWeb;
	}

	public String getBreveDescripcion() {
		return breveDescripcion;
	}

	public void setBreveDescripcion(String breveDescripcion) {
		this.breveDescripcion = breveDescripcion;
	}
	
	@Transient
	public FileBean getLogo() {
		return logo;
	}
	
	public void setLogo(FileBean logo) {
		this.logo = logo;
	}
	
	@Transient
	public FileBean getFondo() {
		return fondo;
	}
	
	public void setFondo(FileBean fondo) {
		this.fondo = fondo;
	}

	public boolean isPublicada() {
		return publicada;
	}

	public void setPublicada(boolean publicada) {
		this.publicada = publicada;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "sponsor")
	@Fetch(FetchMode.SELECT)
	public Set<Imagen> getImagens() {
		return this.imagens;
	}

	public void setImagens(Set<Imagen> imagens) {
		this.imagens = imagens;
	}
	
	@Transient
	public String getImagenLogo() {
		for (Imagen i : imagens) {
			if(i.getTipoImagen()==Constantes.IMAGEN_S_LOGO)imagenLogo =i.getNombreArchivo();
		}
		return imagenLogo;
	}

	public void setImagenLogo(String imagenLogo) {
		this.imagenLogo = imagenLogo;
	}
	
	@Transient
	public String getImagenFondo() {
		for (Imagen i : imagens) {
			if(i.getTipoImagen()==Constantes.IMAGEN_S_FONDO)imagenFondo =i.getNombreArchivo();
		}
		return imagenFondo;
	}

	public void setImagenFondo(String imagenFondo) {
		this.imagenFondo = imagenFondo;
	}

}
