package cor.modelo.dominio;

// default package
// Generated 02/10/2017 17:19:21 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import cor.modelo.tipificaciones.IPersistible;
import cor.modelo.utiles.Constantes;
import net.sourceforge.stripes.action.FileBean;

/**
 * Noticia generated by hbm2java
 */
@Entity
@Table(name = "noticia")
public class Noticia implements java.io.Serializable, IPersistible {	

	private Integer idNoticia;
	private String titulo;
	private String copete;
	private Date fecha;
	private String cuerpo;	
	private boolean publicada; 
	
	private FileBean imagenPrincipal;
	
	private String nombreImagenPrincipal;
	
	private List<FileBean> imagenesGrilla;
	
	private Set<Imagen> imagens = new HashSet<Imagen>(0);
	

	public Noticia() {
	}

	public Noticia(String titulo, String copete,  Date fecha,
			String cuerpo) {
		this.titulo = titulo;
		this.copete = copete;
		this.fecha = fecha;
		this.cuerpo = cuerpo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idNoticia", unique = true, nullable = false)
	public Integer getIdNoticia() {
		return this.idNoticia;
	}

	public void setIdNoticia(Integer idNoticia) {
		this.idNoticia = idNoticia;
	}

	@Column(name = "titulo", length = 2000)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "copete", length = 2000)
	public String getCopete() {
		return this.copete;
	}

	public void setCopete(String copete) {
		this.copete = copete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 0)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "cuerpo", length = 65535)
	public String getCuerpo() {
		return this.cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}	
	
	@Transient
	public FileBean getImagenPrincipal() {
		return imagenPrincipal;
	}

	public void setImagenPrincipal(FileBean imagenPrincipal) {
		this.imagenPrincipal = imagenPrincipal;
	}

	public boolean isPublicada() {
		return publicada;
	}

	public void setPublicada(boolean publicada) {
		this.publicada = publicada;
	}
	
	@Transient
	public String getNombreImagenPrincipal() {
		
		for (Imagen i : imagens) {
			if(i.getTipoImagen()==1) return i.getNombreArchivo();
		}
		
		return nombreImagenPrincipal;
	}

	public void setNombreImagenPrincipal(String nombreImagenPrincipal) {
		this.nombreImagenPrincipal = nombreImagenPrincipal;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "noticia")
	public Set<Imagen> getImagens() {
		return this.imagens;
	}

	public void setImagens(Set<Imagen> imagens) {
		this.imagens = imagens;
	}
	
	@Transient
	public List<FileBean> getImagenesGrilla() {
		return imagenesGrilla;
	}

	public void setImagenesGrilla(List<FileBean> imagenesGrilla) {
		this.imagenesGrilla = imagenesGrilla;
	}

}
